name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trigger repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: one-more-task-manager
          repo: compose-stack
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          client_payload: '{}'
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true